### ISSUE TITLE
Error: Cannot read property 'GoogleApiAvailability' of undefined

### ISSUE THREAD

**Issue by DavidHLau** [NativeScript/nativescript-geolocation#109] opened 2018-02-09 02:14 UTC
**From Documentation Example:**  https://docs.nativescript.org/hardware/location

**Android platform**

**Plugin**: nativescript-geolocation    **Latest version: 4.2.3**

**Sample Code:**
```
var geolocation = require("nativescript-geolocation"); 
  var location = geolocation.getCurrentLocation({ desiredAccuracy: 3, updateDistance: 10, maximumAge: 20000, timeout: 20000 }).
        then(function (loc) {
            if (loc) {
                alert("Current location is: " + loc);
            }
        }, function (e) {
            alert("Error: " + e.message); console.log("Error: " + e.message);
        });


geolocation.getCurrentLocation() **Returns:**
```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}__proto__: Promise[[PromiseStatus]]: "pending"[[PromiseValue]]: undefined

**Comment by atheros** [comment] 2018-02-12 11:05
I'm getting similar error.

Test code:
```typescript
import { Component, OnInit } from "@angular/core";
import * as geolocation from 'nativescript-geolocation';
import { Accuracy } from 'tns-core-modules/ui/enums';

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent implements OnInit {

    ngOnInit(): void {
        console.log('checking if geolocation is enabled');
        geolocation.isEnabled().then(enabled => {
            console.log('isEnabled =', enabled);
            if (enabled) {
               this.watch();
            } else {
               this.request();
            }
        }, e => {
            console.log('isEnabled error', e);
            this.request();
        });
    }

    request() {
        console.log('enableLocationRequest()');
        geolocation.enableLocationRequest().then(() => {
            console.log('location enabled!');
            this.watch();
        }, e => {
            console.log('Failed to enable', e);
        });
    }

    watch() {
        console.log('watchLocation()');
        geolocation.watchLocation(position => {
            console.log(position);
        }, e => {
            console.log('failed to get location');
        }, {
            desiredAccuracy: Accuracy.high,
            minimumUpdateTime: 500
        });
    }
}
```

I do get the allow/deny dialog once, but nothing happens afterwards or on application restart, just the error message:

**Comment by MeMartijn** [comment] 2018-02-18 14:03
I'm also getting a similar error. I have not yet found a solution though.

**Comment by DimitarTachev** [comment] 2018-02-19 14:00
Hi guys,

Your code snippets look fine and we are not able to reproduce such exception on our side. Could you provide us with some steps to reproduce the issue in the Demo app of the plugin or upload a sample app demonstrating the exception?

There is a similar issue (#93) with the first app build when the plugin is used along with the Firebase one. I suggest you delete your `platforms` folder and rebuild your apps as this also looks like an issue in the native dependencies during the app build.

**Comment by rindrasakti** [comment] 2018-02-22 05:47
When I use watchLocation
it produce error
and the error point me to :
var googleApiAvailability = com.google.android.gms.common.GoogleApiAvailability.getInstance();
var resultCode = googleApiAvailability.isGooglePlayServicesAvailable(application_1.android.context);

System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err: Error: Cannot watch location. Call "enableLocationRequest" first
System.err: File: "file:///data/data/org.nativescript.Tekmo/files/app/tns_module
s/nativescript-geolocation/geolocation.js, line: 130, column: 8
System.err: StackTrace:
System.err:     Frame: function:'watchLocation', file:'file:///data/data/org.nat
ivescript.Tekmo/files/app/tns_modules/nativescript-geolocation/geolocation.js',
line: 130, column: 15
System.err:     Frame: function:'exports.onLoaded', file:'file:///data/data/org.
nativescript.Tekmo/files/app/views/lokasi/lokasi.js', line: 17, column: 24
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org
.nativescript.Tekmo/files/app/tns_modules/tns-core-modules/data/observable/obser
vable.js', line: 103, column: 23
System.err:     Frame: function:'Observable._emit', file:'file:///data/data/org.
nativescript.Tekmo/files/app/tns_modules/tns-core-modules/data/observable/observ
able.js', line: 120, column: 18
System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org
.nativescript.Tekmo/files/app/tns_modules/tns-core-modules/ui/core/view-base/vie
w-base.js', line: 202, column: 14
System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.nat
ivescript.Tekmo/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', li
ne: 62, column: 35
System.err:     Frame: function:'Page.onLoaded', file:'file:///data/data/org.nat
ivescript.Tekmo/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 1
05, column: 35
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data
/org.nativescript.Tekmo/files/app/tns_modules/tns-core-modules/ui/core/view-base
/view-base.js', line: 360, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org
.nativescript.Tekmo/files/app/tns_modules/tns-core-modules/ui/core/view-base/vie
w-base.js', line: 346, column: 14
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView',
file:'file:///data/data/org.nativescript.Tekmo/files/app/tns_modules/tns-core-mo
dules/ui/frame/frame.js', line: 504, column: 24
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data
/data/org.nativescript.Tekmo/files/app/tns_modules/tns-core-modules/ui/frame/fra
gment.js', line: 27, column: 38
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)

System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
System.err:     at android.app.Fragment.performCreateView(Fragment.java:2236)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:978)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:1153)
System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:800)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentMa
nager.java:1562)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:48
7)
System.err:     at android.os.Handler.handleCallback(Handler.java:815)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
System.err:     at android.os.Looper.loop(Looper.java:207)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5692)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Zy
goteInit.java:908)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
ActivityManager: Process org.nativescript.Tekmo (pid 2516) has died
ActivityManager: SVC-handleAppDiedLocked: app = ProcessRecord{a648892 2516:org.n
ativescript.Tekmo/u0a141}, app.pid = 2516
ActivityManager: cleanUpApplicationRecord -- 2516

**Comment by antoniocanaveral** [comment] 2018-02-27 19:12
Same error: Cannot read property 'getInstance' of undefined, using @atheros code

JS: ANGULAR BOOTSTRAP DONE. 10774
JS: checking if geolocation is enabled
JS: isEnabled error TypeError: Cannot read property 'getInstance' of undefined
JS: Attempt to get permission
JS: Failed to enable TypeError: Cannot read property 'getInstance' of undefined

**Comment by detorresrc** [comment] 2018-02-28 01:46
Hi guys I also encounter this problem, what I did is I removed the android platform and re added again.

**Comment by MeMartijn** [comment] 2018-03-07 18:47
I actually did delete and re-added my android platform, however, now I'm getting the error ```TypeError: format.replace is not a function```...

**Comment by MeMartijn** [comment] 2018-03-07 19:09
So, after a little bit of fiddling, the ```format.replace``` error was caused by trying to console.log both the longitude and latitude in the same statement. Apparently (I'm not sure why), that will not work. 
The following code works if and only if I send a location through the extended controls on the Android emulator:
```(javascript)
geolocation.isEnabled().then((available) => {
      if (available) {
        let location = geolocation.getCurrentLocation({desiredAccuracy: 3, updateDistance: 10, maximumAge: 20000, timeout: 20000})
          .then((loc) => {
            console.log(loc.longitude);
            console.log(loc.latitude);
          }, (e) => {
            console.log(e);
          })
      } else {
        console.log('Location services not enabled');
      }
    })
```
Without sending the location through the simulator, I'll get a timeout while searching for my location. It actually works on a real device.

**Comment by nsplugins** [comment] 2018-04-13 13:11
Closing since it seems that the issue is solved.

**Closed by nsplugins** 2018-04-13 13:11 UTC
Labels: backlog, bug, needs more info
