### ISSUE TITLE
zone-nativescript ERROR on with angular and iOS simulator

### ISSUE THREAD

**Issue by aturan23** [NativeScript/nativescript-geolocation#141] opened 2018-06-26 07:34 UTC
When I run it on Android get request work correctly. But on IOS it return nativescript error(not server).

`{"line": 994,"column": 38,"sourceURL": "file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js"`

### Which platform(s) does your issue occur on?
- iOS 11.4 Iphone 6 emulator 

### Please, provide the following version numbers that your issue occurs with:
```
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 4.0.1 and the latest available version is 4.1.1.
✔ Component tns-core-modules has 4.1.0 version and is up to date.
✔ Component tns-android has 4.1.3 version and is up to date.
✔ Component tns-ios has 4.1.1 version and is up to date.

"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "install": "^0.11.0",
    "nativescript-angular": "^5.3.0",
    "nativescript-drop-down": "^4.0.0",
    "nativescript-filter-select": "^1.2.9",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-fontawesome": "^1.0.0",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-open-app": "^0.2.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-pulltorefresh": "^2.1.0",
    "nativescript-ripple": "^2.0.0",
    "nativescript-snackbar": "^2.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^3.7.0",
    "nativescript-ui-dataform": "^3.6.0",
    "nativescript-ui-sidedrawer": "^3.5.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.5.0",
    "rxjs-compat": "^6.2.0",
    "tns-core-modules": "^4.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.5.5",
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.11.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-cli": "~2.0.14",
    "webpack-sources": "~1.1.0"
  }

```
### Is there any code involved? 
```
{
"line": 994,
"column": 38,
"sourceURL": "file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js",
"originalStack": "ZoneAwareError@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:994:38\nfile:///app/tns_modules/tns-core-modules/http/http-request/http-request.js:87:37\nUIApplicationMain@[native code]\nstart@file:///app/tns_modules/tns-core-modules/application/application.js:264:26\nrun@file:///app/tns_modules/tns-core-modules/application/application.js:284:10\nbootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:158:26\nbootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:92:38\nbootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:81:26\nanonymous@file:///app/main.js:7:57\nevaluate@[native code]\nmoduleEvaluation@[native code]\n[native code]\npromiseReactionJo
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:569:26: Unhandled Promise rejection: A error occured ; Zone: <root> ; Task: Promise.then ; Value: Error: A error occured HttpError@file:///app/shared/error/http.error.js:5:14 [<root>]
httpResponseHandler@file:///app/helpers/httpResponseHandler.js:63:38 [<root>]
onHttpStreamError@file:///app/shared/http/http.service.js:118:58 [<root>]
onHttpStreamError@[native code] [<root>]
error@file:///app/tns_modules/rxjs/operators/catchError.js:104:39 [<root>]
_error@file:///app/tns_modules/rxjs/Subscriber.js:132:31 [<root>]
error@file:///app/tns_modules/rxjs/Subscriber.js:106:24 [<root>]
onError@file:///app/tns_modules/@angular/http/bundles/http.umd.js:1641:39 [<root>]
file:///app/tns_modules/tns-core-modules/xhr/xhr.js:151:26 [<root>]
forEach@[native code] [<root>]
emitEvent@file:///app/tns_modules/tns-core-modules/xhr/xhr.js:150:25 [<root>]
_setReadyState@file:///app/tns_modules/tns-core-modules/xhr/xhr.js:218:31 [<root>]
file
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:571:22: Error: Uncaught (in promise): Error: A error occured
HttpError@file:///app/shared/error/http.error.js:5:14 [<root>]
httpResponseHandler@file:///app/helpers/httpResponseHandler.js:63:38 [<root>]
onHttpStreamError@file:///app/shared/http/http.service.js:118:58 [<root>]
onHttpStreamError@[native code] [<root>]
error@file:///app/tns_modules/rxjs/operators/catchError.js:104:39 [<root>]
_error@file:///app/tns_modules/rxjs/Subscriber.js:132:31 [<root>]
error@file:///app/tns_modules/rxjs/Subscriber.js:106:24 [<root>]
onError@file:///app/tns_modules/@angular/http/bundles/http.umd.js:1641:39 [<root>]
file:///app/tns_modules/tns-core-modules/xhr/xhr.js:151:26 [<root>]
forEach@[native code] [<root>]
emitEvent@file:///app/tns_modules/tns-core-modules/xhr/xhr.js:150:25 [<root>]
_setReadyState@file:///app/tns_modules/tns-core-modules/xhr/xhr.js:218:31 [<root>]
file:///app/tns_modules/tns-core-modules/xhr/xhr.js:74:37 [<root

```

**Comment by tsonevn** [comment] 2018-07-03 10:38
Hi @aturan23,
I tested your case with latest NativeScript 4.1 and nativescript-geolocation v.4.2.6, however, was unable to recreate any issue with the plugin. For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow us to recreate the issue. 
[Archive.zip](https://github.com/NativeScript/nativescript-geolocation/files/2158874/Archive.zip)

**Comment by abhayastudios** [comment] 2018-07-25 12:02
I had the same (see issue #139), seems to be an issue with the iOS simulator only.

**Comment by tsonevn** [comment] 2018-10-16 06:40
Hi @aturan23 @abhayastudios,
Are you still able to recreate the issue with the latest `nativescript-geolocation` version `4.3.1`?

**Comment by abhayastudios** [comment] 2018-10-16 12:36
@tsonevn unfortunately still happening indeed...

**Comment by tsonevn** [comment] 2018-10-17 06:37
Hi @abhayastudios, 
I have tested the case with our [demo](https://github.com/NativeScript/nativescript-geolocation/tree/master/demo) project on iOS simulator(iPhone 7 iOS 12), however, was unable to hit this problem. Do you have any sample project, which can be used for recreating the issue?

**Comment by abhayastudios** [comment] 2018-10-17 10:54
@tsonevn I'll try to reproduce in a minimal project, although as I wrote in issue #139 as long as this happens only on the simulator, it is not that important to me.

**Comment by abhayastudios** [comment] 2018-10-17 15:30
@tsonevn I was able to reproduce the problem with your sample [project](https://github.com/NativeScript/nativescript-geolocation/files/2158874/Archive.zip). The things is that the first time when the iOS simulator runs, it works fine. However, if you cause the app to restart (through livesync or running `tns run ios` again) without closing the simulator(!), then also with your sample app I will get `Timeout while searching for location!`.

Hope this helps.

**Comment by abhayastudios** [comment] 2018-10-18 10:09
@tsonevn I has always been enabled (for me it is set to Freeway Drive). I remind you that the first time the simulator starts it works just fine.

**Closed** 2018-10-19 10:59 UTC
Labels: needs more info
