### ISSUE TITLE
enableLocationRequest does not return on enabling or denying

### ISSUE THREAD

**Issue by h43z** [NativeScript/nativescript-geolocation#71] opened 2017-09-11 14:53 UTC
It does resolve if location is already enabled.

But it does neither reject if location permission is denied or resolve if permission was granted and location was enabled.

Or am I doing something wrong?

```
geolocation.enableLocationRequest()
  .then(resolved => {
    console.log('resolved')
  })
  .catch(rejected =>{
    console.log('rejected')
  })
```

**Comment by davidpronk** [comment] 2017-09-20 12:27
https://github.com/NativeScript/nativescript-geolocation/issues/37

**Comment by radeva** [comment] 2017-09-20 13:31
Closing the issue since it's duplicate of #37

**Closed by radeva** 2017-09-20 13:31 UTC

**Comment by h43z** [comment] 2017-09-20 14:06
the please reopen #37

**Comment by h43z** [comment] 2017-09-20 14:36
#37 does not work for me (I can only test Android).
Can one of the issues be reopened?

**Comment by ickata** [comment] 2017-11-01 09:35
I confirm that `enableLocationRequest` promise is never resolved on Android. I am testing on 7.1 emulator. 

```
      geolocation.enableLocationRequest().then( function () {
         // I never get here...
      });
```

**Comment by ickata** [comment] 2017-11-01 10:00
@radeva I'm not sure if GitHub sends notifications for comments in closed issues, therefore I tag you...

**Comment by radeva** [comment] 2017-11-01 12:06
Hi @ickata 

Could you open a new issue using the issue template? You can also link this one and #37 there.

Thanks!

**Comment by ickata** [comment] 2017-11-01 12:18
#91
