### ISSUE TITLE
Version 0.0.10 gives build error with tns 2.0

### ISSUE THREAD

**Issue by firecube** [NativeScript/nativescript-geolocation#16] opened 2016-05-04 09:16 UTC
Hi,

I get the error "Processing node_modules failed. TypeError: Invalid Version: 2.0" with version 0.0.10 of the plugin on tns version 2.0.

Downgrading to 0.0.8 of the plugin works fine.

Thanks, Simon

**Comment by Jayuda** [comment] 2016-05-04 13:38
Yes, its error to on my project and work well on 0.0.8

**Comment by NextStepToUp** [comment] 2016-05-06 17:23
Change the package.json with the next values: `"nativescript": {
    "platforms": {
      "android": "2.0.0",
      "ios": "2.0.0"
    }
  },`

**Comment by glueckandi** [comment] 2016-05-09 19:18
I had the same error like firecube.

Changing the package.json line or upgrading to 0.0.11 version,
throws a different error.
(see attached file)

[Error.txt](https://github.com/NativeScript/nativescript-geolocation/files/255686/Error.txt)

[package.json.txt](https://github.com/NativeScript/nativescript-geolocation/files/255692/package.json.txt)

**Comment by nsndeck** [comment] 2016-05-13 08:12
The issue is fixed with the new 0.0.11 version.

**Closed by nsndeck** 2016-05-13 08:12 UTC
