### ISSUE TITLE
IOS doesn't work in the background

### ISSUE THREAD

**Issue by karo-dc** [NativeScript/nativescript-geolocation#228] opened 2019-07-12 15:18 UTC
### Which platform(s) does your issue occur on?
- iOS 
- iOS 12.3.1
- device. iPhone X

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.4.2
- Cross-platform modules: 5.4.3
- Runtime(s): 5.4.0
- Plugin(s): 5.1.0
It's the demo app provided.

I added in info.plist background modes "location".

Click on the startMonitoring (the way is shown in the demo app, and I add iosAllowsBackgroundLocationUpdates: true option), then I push the app into background. In the callback of startMonitoring I write in a file when the location is changed, but it's not updating the file when in background.

### Is there any code involved? 
The code is the same as your demo version provided in github.

**Comment by Prefix1802** [comment] 2019-07-21 21:47
in my project it is working in the background. log your location to console to see if it registers lats and longs.

**Comment by zbranzov** [comment] 2019-08-06 15:39
I'm closing this as duplicate of https://github.com/NativeScript/nativescript-geolocation/issues/176
If @Prefix1802  can assist you further please communicate in the other thread

**Closed by zbranzov** 2019-08-06 15:39 UTC
