### ISSUE TITLE
Current location permission dialog disappears too quickly in ios

### ISSUE THREAD

**Issue by monicaarepo** [NativeScript/nativescript-geolocation#230] opened 2019-07-25 10:51 UTC
I am developing android and ios application using the native script angular. I am using the geolocation plugin for access to the location, but the location permission dialog was disappeared too quickly in ios. Help me to fix the issue.

**Comment by elena-p** [comment] 2019-07-29 15:23
Hi @monicaarepo,

I was not able to reproduce the described issue. Does it happen in the [demo-angular](https://github.com/NativeScript/nativescript-geolocation/blob/master/demo-angular/src/app/home/home.component.ts#L26) app in this repo? If not - could you provide us a sample app so that we could investigate further.

**Comment by RajkumarRepo** [comment] 2019-08-20 14:42
If Location Services Off then call geolocation.enableLocationRequest() it displays the dialogue but it was closed too quickly in angular.

**Comment by elena-p** [comment] 2019-09-13 11:34
HI @monicaarepo, @RajkumarRepo,

We are still unable to reproduce this issue. Could you share on what device/simulator does automatic closing of the permission dialog happen?

**Comment by tgpetrov** [comment] 2019-10-01 08:13
Closing due to inactivity

**Closed by tgpetrov** 2019-10-01 08:13 UTC
Labels: needs more info
